title: My first GitHub Page
author: CHOI KaHou
email: my-fake-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Have written an awesome description for the new site here. I editted this
  line in _config.yml. It appeared in the document head meta (for
  Google search results) and in the feed.xml site description.

# social links
twitter_username: my-fake-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  my-fake-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
